### ISSUE TITLE
py-cpuinfo currently only works on X86 and some ARM/PPC/S390X CPUs

### ISSUE THREAD

**Issue by LittleRandom** [benc-uk/python-demoapp#13]
There is an error for if you run 
```
make test
``` 

One of the packages does not work with M1 Macs, currently. Just wanted to note that.

**Comment by ritazcx** [comment]
how can we fix this? I am using this project for my learning. Got stuck with this error. Appreciate for any help!

**Comment by benc-uk** [comment]
I'm no longer maintaining this code, feel free to make a fork and find your own fix
