### ISSUE TITLE
 ERROR collecting test session _________________________________ /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py:127: in import_module     return _bootstrap._gcd_import(name[level:], package, level)

### ISSUE THREAD

**Issue by MaherOMRI** [benc-uk/python-demoapp#3]
Hello All,

When i run the command 'make test' i get this failure message, can any one support?
`ERROR collecting test session _________________________________
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

<frozen importlib._bootstrap>:1014: in _gcd_import
    ???

<frozen importlib._bootstrap>:991: in _find_and_load
    ???

<frozen importlib._bootstrap>:961: in _find_and_load_unlocked
    ???

<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???

<frozen importlib._bootstrap>:1014: in _gcd_import
    ???

<frozen importlib._bootstrap>:991: in _find_and_load
    ???

<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???

<frozen importlib._bootstrap>:671: in _load_unlocked
    ???

<frozen importlib._bootstrap_external>:783: in exec_module
    ???

<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???

src/app/__init__.py:1: in <module>
    from flask import Flask

src/.venv/lib/python3.8/site-packages/flask/__init__.py:14: in <module>
    from jinja2 import escape

E   ImportError: cannot import name 'escape' from 'jinja2' (/Users/paaaaath/python-demoapp/src/.venv/lib/python3.8/site-packages/jinja2/__init__.py)

==================================== short test summary info ====================================
ERROR  - ImportError: cannot import name 'escape' from 'jinja2' (/Users/maher_omri/Documents/W...
!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

======================================= 1 error in 0.60s ========================================

make: *** [test] Error 2`

**Comment by dotza1** [comment]
Try updating Flask in /src/requirements.txt to 2.1.0
There is some dependency issue with older version of Flask, better answered here:
https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2

**Comment by ptrpl4** [comment]
it should be fixed with this PR https://github.com/benc-uk/python-demoapp/pull/4
@benc-uk pls verify and merge when you have time for it.
Thanks!
